package controllers;

import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.input.MouseEvent;
import modeles.Societe;
import utiles.Connexion;
import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class Liste_entite_forestiereController implements Initializable{
	Connection cnx;
	public PreparedStatement st;
	public ResultSet result;
	
	
	@FXML
	private TableView<Societe> table_entites;
	@FXML
	private TableColumn<Societe, Integer> t_num;
	@FXML
	private TableColumn<Societe, String> t_raison_sociale;
	@FXML
	private TableColumn<Societe, String> t_num_registre;
	@FXML
	private TableColumn<Societe, String> t_num_contribuable;
	@FXML
	private TableColumn<Societe, Integer> t_arrondissement;
	@FXML
	private TableColumn<Societe, String> t_email;
	@FXML
	private TableColumn<Societe, String> t_telephone;
	@FXML
	private TableColumn<Societe, String> t_adresse;
	@FXML
	private TextField search;
	@FXML
	private Button btn_ajouter;
	@FXML
	private Button btn_modifier;
	@FXML
	private Button btn_supprimer;
	@FXML
	private Button btn_visualiser;
	
	
	public ObservableList<Societe> data = FXCollections.observableArrayList();
	

	// Event Listener on Button[#btn_ajouter].onMouseClicked
	@FXML
	public void add(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btn_modifier].onMouseClicked
	@FXML
	public void modify(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btn_supprimer].onMouseClicked
	@FXML
	public void delete(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btn_visualiser].onMouseClicked
	@FXML
	public void view(MouseEvent event) {
		// TODO Autogenerated
	}
	
	public void showSociete() {
		String sql="select * from societe";
		try {
			st=cnx.prepareStatement(sql);
			result=st.executeQuery();
			while(result.next()) {
				data.add(new Societe(result.getInt("idsociete"),result.getString("raisonsociale"),result.getString("numregcommerce"),result.getString("numcontribuable"),result.getInt("arrondissement"),result.getString("email"),result.getString("telephone"),result.getString("adresse")));}
				
		} catch (SQLException e) {
			e.printStackTrace();
		}
		t_num.setCellValueFactory(new PropertyValueFactory<Societe, Integer>("idsociete"));
		t_raison_sociale.setCellValueFactory(new PropertyValueFactory<Societe, String>("raisonsociale"));
		t_num_registre.setCellValueFactory(new PropertyValueFactory<Societe, String>("numregcommerce"));
		t_num_contribuable.setCellValueFactory(new PropertyValueFactory<Societe, String>("numcontribuable"));
		t_arrondissement.setCellValueFactory(new PropertyValueFactory<Societe, Integer>("arrondissement"));
		t_email.setCellValueFactory(new PropertyValueFactory<Societe, String>("email"));
		t_telephone.setCellValueFactory(new PropertyValueFactory<Societe, String>("telephone"));
		t_adresse.setCellValueFactory(new PropertyValueFactory<Societe, String>("adresse"));
		table_entites.setItems(data);
		
	}
	
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		cnx = Connexion.connexionDB();
		showSociete();
		
	}
}
